version: '3'
services:
  nginx:
    image: "nginx:alpine"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/opt/app
    links:
      - web
    ports:
      - "80:80"
  web:
    build:
        context: .
        dockerfile: web.dockerfile
    image: web:latest
    volumes:
      - .:/opt/app
    links:
      - db
  db:
    image: "mysql:5.7"
    volumes:
      - ./db:/var/lib/mysql
      - ./application/_installation:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
  composer:
    image: "composer:latest"
    volumes:
      - .:/app
    command: ['install', '--ignore-platform-reqs', '--no-scripts']